### ISSUE TITLE
启动main.js时报错

### ISSUE THREAD

**Issue by NyanNyanNyan114514** [ArsFy/katonei_bot#1]
![image](https://user-images.githubusercontent.com/56568297/162612342-f2e7871d-75a8-4d92-82f6-9d5f4eb2a2a7.png)

**Comment by arsfy** [comment]
Bot 使用NoSQL DB (Mongo)，請先加圖以初始化database結構後再使用
如何加圖參考 README 或者 Bot /start 內的加圖命令
